# Generated by Django 6.0.5 on 2026-08-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=6)),
                ('id_proof', models.FileField(upload_to='documents/id_proof/')),
                ('address_proof', models.FileField(upload_to='documents/address_proof/')),
                ('ownership_proof', models.FileField(upload_to='documents/ownership_proof/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='users.users')),
            ],
        ),
    ]
