# Generated by Django 6.0.5 on 2026-08-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connection',
        ),
    ]
