# Generated by Django 6.1 on 2026-09-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_rename_connections_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ACTIVE', 'active'), ('DISCONNECTED', 'disconnected')], default='PENDING', max_length=20),
        ),
    ]
