# Generated by Django 6.1 on 2026-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='consumer_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
