# Generated by Django 6.1 on 2026-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_connection_consumer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
