# Generated by Django 6.0.5 on 2026-08-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_rename_connections_connection'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobileNumber',
            new_name='mobile_number',
        ),
    ]
