# Generated by Django 6.0.5 on 2026-08-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='meter_reading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='meter_readings.meterreading'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='SUCCESS', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='billing.bill')),
            ],
        ),
    ]
