# Generated by Django 6.1 on 2026-09-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='water_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
