# Generated by Django 6.1 on 2026-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('IN_PROGRESS', 'in progress'), ('RESOLVED', 'resolved'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
