# Generated by Django 6.1 on 2026-09-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
